In [ ]:
import pandas as pd
import numpy as np

In [ ]:
population_density = pd.read_csv('D:/graduate/DNA/data/서울시 인구밀도.csv')
population_density.head()

  동별(1) 동별(2) 동별(3)   인구 (명)  면적 (㎢)  인구밀도 (명/㎢)
0    합계    소계    소계  9736027  605.24       16086
1    합계   종로구    소계   153789   23.91        6431
2    합계   종로구   사직동     9636    1.23        7834
3    합계   종로구   삼청동     2739    1.49        1838
4    합계   종로구   부암동     9782    2.27        4309

In [ ]:
elder = pd.read_csv('D:/graduate/DNA/data/서울시 동별 고령자.csv')
elder.head()

  동별(1) 동별(2) 동별(3)    전체인구  65세이상 인구
0    합계   종로구    소계  153789     27818
1    합계   종로구   사직동    9636      1774
2    합계   종로구   삼청동    2739       625
3    합계   종로구   부암동    9782      1802
4    합계   종로구   평창동   18329      3435

In [ ]:
alone = pd.read_csv('D:/graduate/DNA/data/서울시 동별 독거노인_소계.csv')
alone.head()

   동별(1) 동별(2) 동별(3)      소계  국민기초생활보장 수급권자  저소득노인   일   반
0  서울특별시    소계    소계  392351         110183  14471  267697
1  서울특별시   종로구    소계    8573           1839    337    6397
2  서울특별시   종로구   사직동     490             60     10     420
3  서울특별시   종로구   삼청동     189             17      6     166
4  서울특별시   종로구   부암동     418             61     20     337

# 변수 추출

### 동별 총인구

In [ ]:
# 동별 총인구
population = population_density.iloc[:,2:4]
population.head()
print(population.shape)

# 동별 소계 제외
population = population[population['동별(3)'] != '소계'] 
print(population.shape)
population.head()

(452, 2)
(426, 2)

  동별(3)  인구 (명)
2   사직동    9636
3   삼청동    2739
4   부암동    9782
5   평창동   18329
6   무악동    8297

In [ ]:
#동을 index 로 만듦 (추후 사칙연산을 위해)
population_index = population.set_index('동별(3)')
population_index

       인구 (명)
동별(3)
사직동      9636
삼청동      2739
부암동      9782
평창동     18329
무악동      8297
...       ...
천호2동    33753
길동      45973
강일동     32982
상일1동    38929
상일2동    10200

[426 rows x 1 columns]

In [ ]:
#신사동이 2개 있는 문제!!
sorted(population_index.index)[243:250]

#관악구 - 신사동
#강남구 - 신사동

['신사1동', '신사2동', '신사동(1)', '신사동(2)', '신수동', '신원동', '신월1동']

### 동별 면적

In [ ]:
# 동별 면적
area = population_density.iloc[:,[2,4]]
area.head()
print(area.shape)

# 동별 소계 제외
area = area[area['동별(3)'] != '소계']
print(area.shape)
area.head()

(452, 2)
(426, 2)

  동별(3)  면적 (㎢)
2   사직동    1.23
3   삼청동    1.49
4   부암동    2.27
5   평창동    8.87
6   무악동    0.36

In [ ]:
#동을 index 로 만듦 (추후 사칙연산을 위해)
area_index = area.set_index('동별(3)')
area_index

       면적 (㎢)
동별(3)
사직동      1.23
삼청동      1.49
부암동      2.27
평창동      8.87
무악동      0.36
...       ...
천호2동     1.57
길동       2.17
강일동      2.26
상일1동     2.65
상일2동     0.54

[426 rows x 1 columns]

### 동별 65세 이상 인구

In [ ]:
# 동별 65세 이상 인구
over_65 = elder.iloc[:, [2, 4]]
print(over_65.shape)
over_65.head()

# 동별 소계 제외
over_65 = over_65[over_65['동별(3)'] != '소계']
print(over_65.shape)
over_65.head()

(451, 2)
(426, 2)

  동별(3)  65세이상 인구
1   사직동      1774
2   삼청동       625
3   부암동      1802
4   평창동      3435
5   무악동      1424

In [ ]:
#동을 index 로 만듦 (추후 사칙연산을 위해)
over_65_index = over_65.set_index('동별(3)')
over_65_index

       65세이상 인구
동별(3)
사직동        1774
삼청동         625
부암동        1802
평창동        3435
무악동        1424
...         ...
암사1동       6063
천호2동       5913
길동         7986
상일1동       4396
상일2동         14

[426 rows x 1 columns]

### 동별 독거노인 인구

In [ ]:
# 동별 독거노인
alone_all = alone.iloc[:, [2,3]]
alone_all.head()
print(alone_all.shape)

# 동별 소계 제외
alone_all = alone_all[alone_all['동별(3)'] != '소계']
print(alone_all.shape)
alone_all.head()

(452, 2)
(426, 2)

  동별(3)   소계
2   사직동  490
3   삼청동  189
4   부암동  418
5   평창동  703
6   무악동  291

In [ ]:
#동을 index 로 만듦 (추후 사칙연산을 위해)
alone_all_index = alone_all.set_index('동별(3)')
alone_all_index.columns=['총독거노인']
alone_all_index

       총독거노인
동별(3)
사직동      490
삼청동      189
부암동      418
평창동      703
무악동      291
...      ...
천호2동    1683
길동      1719
강일동     1091
상일1동     609
상일2동     392

[426 rows x 1 columns]

### 동별 국민기초생활 수급권자 독거노인 인구

In [ ]:
# 동별 국민기초생활 수급권자 독거노인
alone_basic = alone.iloc[:, [2,4]]
alone_basic.head()
print(alone_basic.shape)

# 동별 소계 제외
alone_basic = alone_basic[alone_basic['동별(3)'] != '소계']
print(alone_basic.shape)
alone_basic.head()

(452, 2)
(426, 2)

  동별(3)  국민기초생활보장 수급권자
2   사직동             60
3   삼청동             17
4   부암동             61
5   평창동             48
6   무악동             59

In [ ]:
#동을 index 로 만듦 (추후 사칙연산을 위해)
alone_basic_index = alone_basic.set_index('동별(3)')
alone_basic_index.columns=['국민기초생활 독거노인']
alone_basic_index

       국민기초생활 독거노인
동별(3)
사직동             60
삼청동             17
부암동             61
평창동             48
무악동             59
...            ...
천호2동           593
길동             410
강일동            486
상일1동           100
상일2동           139

[426 rows x 1 columns]

### 동별 저소득 독거노인 인구

In [ ]:
# 동별 저소득 독거노인
alone_lowinc = alone.iloc[:, [2,5]]
alone_lowinc.head()
print(alone_lowinc.shape)

# 동별 소계 제외
alone_lowinc = alone_lowinc[alone_lowinc['동별(3)'] != '소계']
print(alone_lowinc.shape)
alone_lowinc.head()

(452, 2)
(426, 2)

  동별(3)  저소득노인
2   사직동     10
3   삼청동      6
4   부암동     20
5   평창동     22
6   무악동     11

In [ ]:
#동을 index 로 만듦 (추후 사칙연산을 위해)
alone_lowinc_index = alone_lowinc.set_index('동별(3)')
alone_lowinc_index.columns=['저소득 독거노인']
alone_lowinc_index

       저소득 독거노인
동별(3)
사직동          10
삼청동           6
부암동          20
평창동          22
무악동          11
...         ...
천호2동         73
길동           49
강일동          67
상일1동         25
상일2동         32

[426 rows x 1 columns]

### 동별 일반 독거노인 인구

In [ ]:
# 동별 일반 독거노인
alone_normal = alone.iloc[:, [2,6]]
alone_normal.head()
print(alone_normal.shape)

# 동별 소계 제외
alone_normal = alone_normal[alone_normal['동별(3)'] != '소계']
print(alone_normal.shape)
alone_normal.head()

(452, 2)
(426, 2)

  동별(3)  일   반
2   사직동    420
3   삼청동    166
4   부암동    337
5   평창동    633
6   무악동    221

In [ ]:
#동을 index 로 만듦 (추후 사칙연산을 위해)
alone_normal_index = alone_normal.set_index('동별(3)')
alone_normal_index.columns=['일반 독거노인']
alone_normal_index

       일반 독거노인
동별(3)
사직동        420
삼청동        166
부암동        337
평창동        633
무악동        221
...        ...
천호2동      1017
길동        1260
강일동        538
상일1동       484
상일2동         2

[426 rows x 1 columns]

# 추가 변수

### 동별 65세 이상 인구 비율

In [ ]:
over_65_ratio = (over_65_index['65세이상 인구'] / population_index['인구 (명)']).to_frame()
over_65_ratio.columns=['65세 이상 인구 비율']
over_65_ratio

       65세 이상 인구 비율
동별(3)
가락1동       0.126439
가락2동       0.132074
가락본동       0.143687
가리봉동       0.158659
가산동        0.102449
...             ...
효창동        0.146613
후암동        0.174832
휘경1동       0.130767
휘경2동       0.160663
흑석동        0.171748

[426 rows x 1 columns]

In [ ]:
over_65_ratio.isna().sum()

65세 이상 인구 비율    0
dtype: int64

In [ ]:
#pandas 에서 사칙연산은 index 기준으로 하기 때문에 순서는 달라도 상관없음
print(over_65_index.index[407:424]) 
print(population_index.index[407:424])

Index(['강일동', '명일1동', '명일2동', '고덕1동', '고덕2동', '암사2동', '암사3동', '천호1동', '천호3동',
       '성내1동', '성내2동', '성내3동', '둔촌1동', '둔촌2동', '암사1동', '천호2동', '길동'],
      dtype='object', name='동별(3)')
Index(['명일1동', '명일2동', '고덕1동', '고덕2동', '암사2동', '암사3동', '천호1동', '천호3동', '성내1동',
       '성내2동', '성내3동', '둔촌1동', '둔촌2동', '암사1동', '천호2동', '길동', '강일동'],
      dtype='object', name='동별(3)')

In [ ]:
different=[]
for i in range(0, 426):
    if over_65_ratio.index[i] != sorted(over_65_index.index)[i]:
        different.append(i)
print(different)

[]

In [ ]:
#새로 만든 ratio 변수에 '신사동' 이 4개나 들어감!!!!
print(sorted(over_65_index.index)[244:250]) 
print(over_65_ratio.index[244:250])

['신사2동', '신사동(1)', '신사동(2)', '신수동', '신원동', '신월1동']
Index(['신사2동', '신사동(1)', '신사동(2)', '신수동', '신원동', '신월1동'], dtype='object', name='동별(3)')

In [ ]:
over_65_ratio[246:249]

        65세 이상 인구 비율
동별(3)
신사동(2)      0.187010
신수동         0.141981
신원동         0.174672

### 동별 65세 이상 인구밀도

In [ ]:
over_65_density = (over_65_index['65세이상 인구'] / area_index['면적 (㎢)']).to_frame()
over_65_density.columns=['65세 이상 인구밀도']
over_65_density

       65세 이상 인구밀도
동별(3)
가락1동   2582.089552
가락2동   4458.333333
가락본동   3372.566372
가리봉동   5192.500000
가산동    1064.285714
...            ...
효창동    3384.090909
후암동    3518.604651
휘경1동   3342.857143
휘경2동   3801.904762
흑석동    3403.571429

[426 rows x 1 columns]

In [ ]:
over_65_density.isna().sum()

65세 이상 인구밀도    0
dtype: int64

##### 신사동 1, 2로 안하면
새로 만든 ratio 변수에 '신사동' 이 4개나 들어감!!!! 

값도 다 다름...

print(sorted(over_65_density.index)[244:250]) 

print(over_65_density[245:249])

### 동별 총독거노인 인구 비율

In [ ]:
alone_all_ratio = (alone_all_index['총독거노인'] / population_index['인구 (명)']).to_frame()
alone_all_ratio.columns=['총독거노인 인구 비율']
alone_all_ratio

       총독거노인 인구 비율
동별(3)
사직동       0.050851
삼청동       0.069003
부암동       0.042732
평창동       0.038355
무악동       0.035073
...            ...
천호2동      0.049862
길동        0.037392
강일동       0.033079
상일1동      0.015644
상일2동      0.038431

[426 rows x 1 columns]

In [ ]:
sorted(alone_all_ratio.index)[244:250]

['신사2동', '신사동(1)', '신사동(2)', '신수동', '신원동', '신월1동']

In [ ]:
#동 이름이 다른 index 추출
different=[]
for i in range(0, 426):
    if alone_all_index.index[i] != population_index.index[i]:
        different.append(i)
print(different)

[]

In [ ]:
#독거노인의 정능1동을 정릉1동으로 바꿈
print(alone_all_index.index[114:118]) 
print(population_index.index[114:118])

Index(['정릉1동', '정릉2동', '정릉3동', '정릉4동'], dtype='object', name='동별(3)')
Index(['정릉1동', '정릉2동', '정릉3동', '정릉4동'], dtype='object', name='동별(3)')

### 동별 총독거노인 인구 밀도

In [ ]:
alone_all_density = (alone_all_index['총독거노인'] / area_index['면적 (㎢)']).to_frame()
alone_all_density.columns=['총독거노인 인구 밀도']
alone_all_density

       총독거노인 인구 밀도
동별(3)
사직동     398.373984
삼청동     126.845638
부암동     184.140969
평창동      79.255919
무악동     808.333333
...            ...
천호2동   1071.974522
길동      792.165899
강일동     482.743363
상일1동    229.811321
상일2동    725.925926

[426 rows x 1 columns]

### 동별 국민기초생활 수급권자 독거노인 비율

In [ ]:
alone_basic_ratio = (alone_basic_index['국민기초생활 독거노인'] / population_index['인구 (명)']).to_frame()
alone_basic_ratio.columns=['국민기초생활 독거노인 비율']
alone_basic_ratio

       국민기초생활 독거노인 비율
동별(3)
사직동          0.006227
삼청동          0.006207
부암동          0.006236
평창동          0.002619
무악동          0.007111
...               ...
천호2동         0.017569
길동           0.008918
강일동          0.014735
상일1동         0.002569
상일2동         0.013627

[426 rows x 1 columns]

### 동별 국민기초생활 수급권자 독거노인 밀도

In [ ]:
alone_basic_density = (alone_basic_index['국민기초생활 독거노인'] / area_index['면적 (㎢)']).to_frame()
alone_basic_density.columns=['국민기초생활 독거노인 밀도']
alone_basic_density

       국민기초생활 독거노인 밀도
동별(3)
사직동         48.780488
삼청동         11.409396
부암동         26.872247
평창동          5.411499
무악동        163.888889
...               ...
천호2동       377.707006
길동         188.940092
강일동        215.044248
상일1동        37.735849
상일2동       257.407407

[426 rows x 1 columns]

### 동별 저소득 독거노인 비율

In [ ]:
alone_lowinc_ratio = (alone_lowinc_index['저소득 독거노인'] / population_index['인구 (명)']).to_frame()
alone_lowinc_ratio.columns=['저소득 독거노인 비율']
alone_lowinc_ratio

       저소득 독거노인 비율
동별(3)
사직동       0.001038
삼청동       0.002191
부암동       0.002045
평창동       0.001200
무악동       0.001326
...            ...
천호2동      0.002163
길동        0.001066
강일동       0.002031
상일1동      0.000642
상일2동      0.003137

[426 rows x 1 columns]

### 동별 저소득 독거노인 밀도

In [ ]:
alone_lowinc_density = (alone_lowinc_index['저소득 독거노인'] / area_index['면적 (㎢)']).to_frame()
alone_lowinc_density.columns=['저소득 독거노인 밀도']
alone_lowinc_density

       저소득 독거노인 밀도
동별(3)
사직동       8.130081
삼청동       4.026846
부암동       8.810573
평창동       2.480271
무악동      30.555556
...            ...
천호2동     46.496815
길동       22.580645
강일동      29.646018
상일1동      9.433962
상일2동     59.259259

[426 rows x 1 columns]

### 동별 일반 독거노인 비율

In [ ]:
alone_normal_ratio = (alone_normal_index['일반 독거노인'] / population_index['인구 (명)']).to_frame()
alone_normal_ratio.columns=['일반 독거노인 비율']
alone_normal_ratio

       일반 독거노인 비율
동별(3)
사직동      0.043587
삼청동      0.060606
부암동      0.034451
평창동      0.034535
무악동      0.026636
...           ...
천호2동     0.030131
길동       0.027407
강일동      0.016312
상일1동     0.012433
상일2동     0.000196

[426 rows x 1 columns]

### 동별 일반 독거노인 밀도

In [ ]:
alone_normal_density = (alone_normal_index['일반 독거노인'] / area_index['면적 (㎢)']).to_frame()
alone_normal_density.columns=['일반 독거노인 밀도']
alone_normal_density

       일반 독거노인 밀도
동별(3)
사직동    341.463415
삼청동    111.409396
부암동    148.458150
평창동     71.364149
무악동    613.888889
...           ...
천호2동   647.770701
길동     580.645161
강일동    238.053097
상일1동   182.641509
상일2동     3.703704

[426 rows x 1 columns]

# 하나의 dataframe 으로

In [ ]:
df = population_index.join([ area_index, over_65_index, over_65_ratio, over_65_density, alone_all_index, alone_basic_index, alone_lowinc_index, alone_normal_index, alone_all_ratio, alone_all_density, alone_basic_ratio, alone_basic_density, alone_lowinc_ratio, alone_lowinc_density, alone_normal_ratio, alone_normal_density])
df

,인구 (명),면적 (㎢),65세이상 인구,65세 이상 인구 비율,65세 이상 인구밀도,총독거노인,국민기초생활 독거노인,저소득 독거노인,일반 독거노인,총독거노인 인구 비율,총독거노인 인구 밀도,국민기초생활 독거노인 비율,국민기초생활 독거노인 밀도,저소득 독거노인 비율,저소득 독거노인 밀도,일반 독거노인 비율,일반 독거노인 밀도
동별(3),,,,,,,,,,,,,,,,,
사직동,9636,1.23,1774,0.184101,1442.276423,490,60,10,420,0.050851,398.373984,0.006227,48.780488,0.001038,8.130081,0.043587,341.463415
삼청동,2739,1.49,625,0.228185,419.463087,189,17,6,166,0.069003,126.845638,0.006207,11.409396,0.002191,4.026846,0.060606,111.409396
부암동,9782,2.27,1802,0.184216,793.832599,418,61,20,337,0.042732,184.140969,0.006236,26.872247,0.002045,8.810573,0.034451,148.458150
평창동,18329,8.87,3435,0.187408,387.260428,703,48,22,633,0.038355,79.255919,0.002619,5.411499,0.001200,2.480271,0.034535,71.364149
무악동,8297,0.36,1424,0.171628,3955.555556,291,59,11,221,0.035073,808.333333,0.007111,163.888889,0.001326,30.555556,0.026636,613.888889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
천호2동,33753,1.57,5913,0.175184,3766.242038,1683,593,73,1017,0.049862,1071.974522,0.017569,377.707006,0.002163,46.496815,0.030131,647.770701
길동,45973,2.17,7986,0.173711,3680.184332,1719,410,49,1260,0.037392,792.165899,0.008918,188.940092,0.001066,22.580645,0.027407,580.645161
강일동,32982,2.26,5321,0.161330,2354.424779,1091,486,67,538,0.033079,482.743363,0.014735,215.044248,0.002031,29.646018,0.016312,238.053097
상일1동,38929,2.65,4396,0.112924,1658.867925,609,100,25,484,0.015644,229.811321,0.002569,37.735849,0.000642,9.433962,0.012433,182.641509
상일2동,10200,0.54,14,0.001373,25.925926,392,139,32,2,0.038431,725.925926,0.013627,257.407407,0.003137,59.259259,0.000196,3.703704

In [ ]:
#df['동별'] = df.index     #동별 index 를 column으로
#df = df.reset_index(drop=True) #index 없앰
#df

,인구 (명),면적 (㎢),65세이상 인구,65세 이상 인구 비율,65세 이상 인구밀도,총독거노인,국민기초생활 독거노인,저소득 독거노인,일반 독거노인,총독거노인 인구 비율,총독거노인 인구 밀도,국민기초생활 독거노인 비율,국민기초생활 독거노인 밀도,저소득 독거노인 비율,저소득 독거노인 밀도,일반 독거노인 비율,일반 독거노인 밀도,동별
0,9636,1.23,1774,0.184101,1442.276423,490,60,10,420,0.050851,398.373984,0.006227,48.780488,0.001038,8.130081,0.043587,341.463415,사직동
1,2739,1.49,625,0.228185,419.463087,189,17,6,166,0.069003,126.845638,0.006207,11.409396,0.002191,4.026846,0.060606,111.409396,삼청동
2,9782,2.27,1802,0.184216,793.832599,418,61,20,337,0.042732,184.140969,0.006236,26.872247,0.002045,8.810573,0.034451,148.458150,부암동
3,18329,8.87,3435,0.187408,387.260428,703,48,22,633,0.038355,79.255919,0.002619,5.411499,0.001200,2.480271,0.034535,71.364149,평창동
4,8297,0.36,1424,0.171628,3955.555556,291,59,11,221,0.035073,808.333333,0.007111,163.888889,0.001326,30.555556,0.026636,613.888889,무악동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,33753,1.57,5913,0.175184,3766.242038,1683,593,73,1017,0.049862,1071.974522,0.017569,377.707006,0.002163,46.496815,0.030131,647.770701,천호2동
422,45973,2.17,7986,0.173711,3680.184332,1719,410,49,1260,0.037392,792.165899,0.008918,188.940092,0.001066,22.580645,0.027407,580.645161,길동
423,32982,2.26,5321,0.161330,2354.424779,1091,486,67,538,0.033079,482.743363,0.014735,215.044248,0.002031,29.646018,0.016312,238.053097,강일동
424,38929,2.65,4396,0.112924,1658.867925,609,100,25,484,0.015644,229.811321,0.002569,37.735849,0.000642,9.433962,0.012433,182.641509,상일1동
425,10200,0.54,14,0.001373,25.925926,392,139,32,2,0.038431,725.925926,0.013627,257.407407,0.003137,59.259259,0.000196,3.703704,상일2동

In [ ]:
df.to_csv('D:/graduate/DNA/data/인구관련2.csv', index=True)