## 드라이브 마운트

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 라이브러리 불러오기

In [3]:
import pandas as pd
import numpy as np

## 데이터 불러오기

In [7]:
dir= '/content/drive/MyDrive/DNA/Data Archive'

df = pd.read_csv(dir+'/최종 선정 행정동.csv')
LH = pd.read_csv(dir+'/LH 서울시 통합 행정동 통합.csv', encoding="cp949")

In [5]:
pd.set_option('display.max_rows', None)

In [8]:
df_lh = pd.merge(df, LH, how = 'inner')
df_lh

,Unnamed: 0,구,동,단지코드,단지명,세대수,동수,임대유형,주택유형,주소,Latitude,Longitude,준공일,입주지정시작일자,입주지정종료일자,위도,경도,비고
0,6,동대문구,장안1동,0,매입다가구(서울동대문구),45,0,기존주택매입임대,NaN,서울특별시 동대문구 장한로26길 85,37.571464,127.076239,2019,43799,NaN,37.571473,127.076357,0
1,7,중랑구,중화2동,0,매입다가구(서울중랑구),30,0,기존주택매입임대,NaN,서울특별시 중랑구 중랑천로 109,37.594838,127.072018,2017,42968,43068,37.594677,127.071947,0
2,7,중랑구,중화2동,0,매입다가구(서울중랑구),30,0,기존주택매입임대,NaN,서울특별시 중랑구 중랑천로 109,37.594838,127.072018,2017,42968,43068,37.594677,127.071947,0
3,7,중랑구,중화2동,0,매입다가구(서울중랑구),30,0,기존주택매입임대,NaN,서울특별시 중랑구 중랑천로 109,37.594838,127.072018,2017,42968,43068,37.594677,127.071947,0
4,24,도봉구,도봉2동,C00211,서울도봉,245,3,건설임대,국민임대,서울특별시 도봉구 도봉로180길 83-14(서울도봉주공아파트),37.682949,127.050719,2002-11-01,2002-12-01,2002-12-20,37.682607,127.050663,0
5,25,노원구,월계2동,C00225,서울월계1,2328,11,건설임대,영구임대+임대상가,서울특별시 노원구 초안산로1길 15 (월계1단지주공영구임대(아)),37.630911,127.054016,1993-09-01,1992-11-10,1992-12-09,37.627271,127.053425,0
6,27,노원구,하계1동,C02208,서울중계9 증축 영구임대주택(주거복지동),60,1,건설임대,영구임대+임대상가,서울특별시 노원구 노원로16길 15(하계동 중계주공9단지아파트),37.642888,127.073736,2017-09-01,2017-09-12,2017-10-11,37.643445,127.073337,0
7,27,노원구,하계1동,C00228,서울중계9,2693,16,건설임대,영구임대+임대상가,서울특별시 노원구 노원로16길 15 (중계9단지주공영구임대아파트),37.642888,127.073736,1992-09-18,1992-09-30,1992-10-29,37.643445,127.073337,0
8,28,노원구,중계4동,C00227,서울중계3,1345,6,건설임대,영구임대+임대상가,서울특별시 노원구 덕릉로 662 (중계3단지주공영구임대아파트),37.656494,127.076034,1991-09-14,1991-09-27,1991-10-26,37.656396,127.076659,0
9,28,노원구,중계4동,C02101,서울중계3 증축 영구임대(주거복지동),130,1,건설임대,영구임대,서울특별시 노원구 덕릉로 662(중계동 주공3단지아파트),37.656494,127.076034,2017-06-27,2016-10-07,2016-11-05,37.656396,127.076659,0
10,33,노원구,중계2.3동,C00226,서울중계1,889,4,건설임대,영구임대+임대상가,서울특별시 노원구 동일로210길 22 (중계동주공영구임대아파트),37.657164,127.072961,1990-12-05,1990-12-15,1991-01-14,37.646908,127.065216,0
11,34,노원구,공릉1동,0,매입다가구(서울노원구),96,0,기존주택매입임대,NaN,서울특별시 노원구 동일로174길 38,37.618935,127.077549,2019,41683,43823,37.618909,127.077592,0
12,42,은평구,역촌동,0,매입다가구(서울은평구),133,0,기존주택매입임대,NaN,서울특별시 은평구 연서로 16,37.600482,126.916346,2020,43840,NaN,37.600555,126.916436,0
13,42,은평구,역촌동,0,매입다가구(서울은평구),39,0,기존주택매입임대,NaN,서울특별시 은평구 연서로16길 3-7,37.610312,126.917490,2018,43335,43432,37.610341,126.917528,0
14,44,마포구,성산2동,C02055,서울가좌 행복주택,362,3,건설임대,행복주택+임대상가,서울특별시 마포구 성암로 36(성산동) 일원 서울가좌 행복주택,37.569152,126.912899,2016-12-28,2017-02-13,2017-04-13,37.569416,126.912461,0
15,48,강서구,등촌3동,C00217,서울등촌9,1464,8,건설임대,영구임대+임대상가,서울특별시 강서구 화곡로63가길 92(등촌동 등촌9단지주공영구임대아파트) (등촌동 ...,37.561533,126.848800,1994-10-01,1994-11-01,1994-11-30,37.561952,126.850209,0
16,48,강서구,등촌3동,C00216,서울등촌7,1156,8,건설임대,영구임대+임대상가,서울특별시 강서구 공항대로43길 104(등촌동 등촌주공7 8단지아파트),37.560731,126.851613,1994-09-16,1994-11-07,1994-12-06,37.560239,126.851694,0
17,48,강서구,등촌3동,C00212,서울등촌1,1692,11,건설임대,영구임대+임대상가,서울특별시 강서구 강서로68길 36 (등촌1단지영구임대아파트),37.564004,126.842372,1994-10-15,1994-11-11,1994-12-10,37.565387,126.842257,0
18,48,강서구,등촌3동,C00215,서울등촌6,559,5,건설임대,공공임대(50년),서울특별시 강서구 화곡로63가길 18 (등촌6단지주공아파트),37.559610,126.848448,1992-01-01,1995-10-30,1995-11-29,37.560006,126.848406,0
19,48,강서구,등촌3동,C00213,서울등촌11,350,8,건설임대,국민임대,서울특별시 강서구 공항대로43길 39 (등촌주공아파트11단지),37.559067,126.849134,2004-09-23,2004-10-22,2004-11-10,37.559290,126.849646,0
20,48,강서구,등촌3동,C00214,서울등촌4,1589,10,건설임대,영구임대+임대상가,서울특별시 강서구 공항대로39길 59 (등촌4단지주공임대아파트),37.561470,126.843500,1995-05-05,1995-05-29,1995-06-28,37.562259,126.842895,0
21,50,강서구,가양3동,C00209,서울가양,2023,12,건설임대,영구임대+임대상가,서울특별시 강서구 허준로 209(가양동 가양7단지아파트) 209 (가양주공영구임대...,37.562211,126.861478,1992-06-30,1992-09-30,1992-10-29,37.561952,126.850209,0
22,53,강서구,화곡1동,0,매입다가구(서울강서구),46,0,기존주택매입임대,NaN,서울특별시 강서구 곰달래로 82,37.531166,126.852460,2013,41177,41613,37.530067,126.841843,0
23,55,구로구,오류2동,0,매입다가구(서울구로구),48,0,기존주택매입임대,NaN,서울특별시 구로구 서해안로 2325,37.491115,126.839593,2015,42107,42191,37.493211,126.842470,0
24,59,영등포구,영등포동,0,매입다가구(서울영등포구),90,0,기존주택매입임대,NaN,서울특별시 영등포구 영등포로49길 9-14,37.519987,126.909772,2018,43005,43803,37.520255,126.909232,0
25,61,동작구,대방동,C00210,서울대방1,947,6,건설임대,영구임대+임대상가,서울특별시 동작구 여의대방로44길 47 (대방1단지주공아파트),37.510763,126.930142,1993-04-12,1993-04-30,1993-05-31,37.509926,126.930425,0
26,62,서초구,양재1동,C01760,서울서초3블록,790,5,건설임대,장기전세+국민임대+영구임대,서울특별시 서초구 양재대로2길 34,37.464496,127.041751,2013-12-07,2013-12-07,2014-01-05,37.457582,127.022167,0
27,62,서초구,양재1동,C00224,서울우면,991,7,건설임대,영구임대+임대상가,서울특별시 서초구 바우뫼로7길 11(우면동 우면주공아파트) 11 주공아파트 (우면동),37.470131,127.024190,1994-07-18,1994-08-11,1994-09-10,37.469862,127.023866,11 주공아파트~ ' 제외
28,64,강남구,수서동,C00221,서울수서,2596,16,건설임대,영구임대+임대상가,서울특별시 강남구 광평로51길 49,37.491035,127.100279,1992-10-19,1992-10-31,1992-11-30,37.492137,127.099752,0
29,65,강남구,세곡동,C01755,서울강남 3블록,1065,15,건설임대,국민임대+영구임대,서울특별시 강남구 자곡로3길 22,37.517236,127.047325,2013-08-31,2013-11-25,2013-12-24,37.469971,127.091020,0
30,65,강남구,세곡동,0,매입다가구(서울강남구),84,0,기존주택매입임대,NaN,서울특별시 강남구 헌릉로569길 3,37.466266,127.116787,2019,43665,43766,37.466807,127.101361,0